# Generated by Django 2.0.4 on 2018-04-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='mode',
            field=models.CharField(default='OUT', max_length=10),
            preserve_default=False,
        ),
    ]
